### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by gavenwan** [yihong0618/run_route_show#1]
Macos 使用brew install pdm 后

1、pdm update 成功
2、接下来运行 pdm run python -m route_show --all报错
报错内容：

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/gaven/run_route_show/route_show/__main__.py", line 1, in <module>
    from route_show.cli import main
  File "/Users/gaven/run_route_show/route_show/cli.py", line 4, in <module>
    from route_show.route_show import RouteShow
  File "/Users/gaven/run_route_show/route_show/route_show.py", line 11, in <module>
    from cairosvg import svg2png  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gaven/run_route_show/.venv/lib/python3.13/site-packages/cairosvg/__init__.py", line 26, in <module>
    from . import surface  # noqa isort:skip
    ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gaven/run_route_show/.venv/lib/python3.13/site-packages/cairosvg/surface.py", line 9, in <module>
    import cairocffi as cairo
  File "/Users/gaven/run_route_show/.venv/lib/python3.13/site-packages/cairocffi/__init__.py", line 60, in <module>
    cairo = dlopen(
        ffi, ('cairo-2', 'cairo', 'libcairo-2'),
        ('libcairo.so.2', 'libcairo.2.dylib', 'libcairo-2.dll'))
  File "/Users/gaven/run_route_show/.venv/lib/python3.13/site-packages/cairocffi/__init__.py", line 57, in dlopen
    raise OSError(error_message)  # pragma: no cover
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: no library called "cairo-2" was found
no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so.2': dlopen(libcairo.so.2, 0x0002): tried: 'libcairo.so.2' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibcairo.so.2' (no such file), '/opt/homebrew/lib/libcairo.so.2' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/lib/libcairo.so.2' (no such file), '/usr/lib/libcairo.so.2' (no such file, not in dyld cache), 'libcairo.so.2' (no such file).  Additionally, ctypes.util.find_library() did not manage to locate a library called 'libcairo.so.2'
cannot load library 'libcairo.2.dylib': dlopen(libcairo.2.dylib, 0x0002): tried: 'libcairo.2.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibcairo.2.dylib' (no such file), '/opt/homebrew/lib/libcairo.2.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/lib/libcairo.2.dylib' (no such file), '/usr/lib/libcairo.2.dylib' (no such file, not in dyld cache), 'libcairo.2.dylib' (no such file).  Additionally, ctypes.util.find_library() did not manage to locate a library called 'libcairo.2.dylib'
cannot load library 'libcairo-2.dll': dlopen(libcairo-2.dll, 0x0002): tried: 'libcairo-2.dll' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibcairo-2.dll' (no such file), '/opt/homebrew/lib/libcairo-2.dll' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/lib/libcairo-2.dll' (no such file), '/usr/lib/libcairo-2.dll' (no such file, not in dyld cache), 'libcairo-2.dll' (no such file).  Additionally, ctypes.util.find_library() did not manage to locate a library called 'libcairo-2.dll'

**Comment by yihong0618** [comment]
cairo 查询怎么安装这个库 cairo

**Comment by gavenwan** [comment]
> cairo 查询怎么安装这个库 cairo

1、sudo port install cairo 提示成功
gaven@GavenMac run_route_show % sudo port install cairo
--->  Computing dependencies for cairo
--->  Cleaning cairo
--->  Scanning binaries for linking errors
--->  No broken files found.
--->  No broken ports found.

2、pdm run还是报错，一样的报错内容，重启macos终端，也是一样的错误内容。

我再尝试用win虚拟机试试

**Comment by gavenwan** [comment]
使用brew install cairo后成功运行项目，不太理解为啥sudo port install cairo成功就不行
