### ISSUE TITLE
生成的视频顺序奇怪

### ISSUE THREAD

**Issue by gavenwan** [yihong0618/run_route_show#2]
[http://58.33.25.126:5555/h5/2024.mp4](http://58.33.25.126:5555/h5/2024.mp4)

1）使用命令pdm run python -m route_show --all --to_png 生成了所有图片
2）使用命令pdm run python -m route_show --video 生成了视频

但是最终视频里的图片顺序并没有按运动时间排序，没找到排序的规律

**Comment by yihong0618** [comment]
- 把图片都删了重新跑一遍
- 只生成 2024 年的不要加 --all

---
我也修复下你可以等等我的最新代码。

**Comment by yihong0618** [comment]
我修复一下一会儿推一下代码

**Comment by yihong0618** [comment]
修复了，拉一下最新代码重新跑一下

**Comment by gavenwan** [comment]
已修复，视频顺序正常了，感谢大佬

**Comment by yihong0618** [comment]
enjoy it
